version: '2.1'

services:
  mysql:
    image: akoller/low-memory-mysql
    container_name: mysql
    mem_limit: 256m
    environment:
      MYSQL_ROOT_PASSWORD: "foobar"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    networks:
      - ehb2_net

  ehb2:
    image: akoller/ehb2
    container_name: ehb2
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 5000:5000
    networks:
      - ehb2_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      mysql:
        condition: service_healthy
    environment:
       PMA_HOST: "mysql"
       MYSQL_ROOT_PASSWORD: "foobar"
    ports:
      - 8080:80
    networks:
      - ehb2_net


networks:
  ehb2_net:
    driver: bridge
